### ISSUE TITLE
import coding

### ISSUE THREAD

**Issue by lss0510** [AyanKumarBhunia/on-the-fly-FGSBIR#1]
Net_Basic_V1 line 5
import encoding
where i can get this？

**Comment by AyanKumarBhunia** [comment]
Comment/delete that line. I did some other experiments(other work) with inception as a backbone feature extractor.  For this work, it has nothing to do with that.

**Comment by zxh19976666** [comment]
> Net_Basic_V1 line 5
> import encoding
> where i can get this？

exm sir  your code is successful to run? if you did it  could you help me？

**Comment by lss0510** [comment]
sorry，It’s too long for me to remember anything about this.



发自我的iPhone


------------------ Original ------------------
